colors = ('blue','yellow','cyan','red','purle','golden','bonesana','silver')
print(len(colors))
print(type(colors))
print(colors[-2])
print(colors[1:7])
a = list(colors)
a [3] = 'black'
colors = tuple (a)
print(a)
s = list(colors)
s.remove ('blue')
colors = tuple (s)
print(s)
